### ISSUE TITLE
Transdecoder error with -G Universal parameter

### ISSUE THREAD

**Issue by LehmannN** [EI-CoreBioinformatics/mikado#312]
Hello !

I have another comment regarding the daijin pipeline. When coming through the `TransDecoder.LongOrfs` step in the `daijin mikado` pipeline, it suddenly stops with the error "Sorry, Universal is not currently supported or recognized.". So I just ran transdecoder out of the daijin pipeline without the `-G Universal` parameter, but I wonder it there is a way to modify the command line ran by `daijin` ? I am using the Mikado conda environment btw and we get the same error for `TransDecoder.Predict`. 

Thanks again help and comments.

**Comment by lucventurini** [comment]
Dear @LehmannN ,

This is really surprising, I automatically check that Daijin runs correctly whenever there is a commit. May I ask which version of TransDecoder you are using? On my workstation `Universal` is explicitly listed as a valid option (with `conda`, `transdecoder=5.5.0=pl526_2`).

**Comment by LehmannN** [comment]
I found that I am running TransDecoder-3.0.1 so that might explain why. I have it installed locally and through the conda environment but the default program that runs is the one installed locally... I am not sure how to fix that but will have a look.

**Comment by LehmannN** [comment]
I realized that in fact I had no installation of `transdecoder` in conda, only a local installation I have been fooled by running mikado inside the conda environment, but since the tool was not in the environment, daijin found it in /usr/bin/. Is there a reason why you don't have `transdecoder` and `mikado` in the `environment.yml` file ?

**Comment by lucventurini** [comment]
Dear @LehmannN ,

Within Daijin, I try to keep the different tool requirements separate, also because there are tools that are incompatible with each other (e.g. I think that `tophat2` requires python2, which would make it incompatible with Mikado itself).
For this reason, Daijin fully implements the `--use-conda` switch present also in Snakemake. Briefly, if the switch is present on the command line, Daijin will create a separate Conda environment for each required tool, including TransDecoder.

I hope this helps.

Kind regards

**Comment by LehmannN** [comment]
Ok, thanks for the explanations !
