### ISSUE TITLE
Keeping model annotations

### ISSUE THREAD

**Issue by 14zac2** [EI-CoreBioinformatics/mikado#340]
Hello!

I am using Mikado with a few sets of genes, one of which has been manually curated and I don't want to lose. In the list.txt file, I specified the 5th column as "True" for this gff file. However, when I complete the pipeline and look for the genes that have been preserved through the pipeline, I do not find all of these genes through grep -c "alias=label_". Is there a way I can preserve these genes while adding annotations from different assemblies on top of them?

Thanks,
Zoe

**Comment by lucventurini** [comment]
Hi @14zac2 

The behaviour of Mikado seems incorrect here then. May I ask you whether the transcripts disappear already in the `mikado_prepared.gtf` or whether they are absent from the final output file of `pick`?

In the latter case, the desired behaviour should be obtainable by adding the command line switch "--only-reference-update" and by adding a score bonus to the reference transcripts themselves.

I hope this helps.

Kind regards

Luca Venturini

**Comment by 14zac2** [comment]
Hi Luca,

Thank you so much for your response! The transcripts do not disappear in `mikado_prepared.gtf`, but are indeed absent from `pick`. I reran `mikado pick` giving my desired transcripts a score of 10, which made most of them appear in the resulting gtf, but not all. Hopefully adding "--only-reference-update" will do the trick, as it sounds like it will!

To clarify, the gtf file I am hoping to update is a list of ~9000 manually curated genes with no isoforms. I would be happy obtaining new isoforms of these genes (as the only isoforms I currently have are the longest isoforms), as well as populating the rest of the genome with genes and transcripts. Will --only-reference-update do this?

Thank you so much for your clarification of this, I really appreciate it!

Cheers,
Zoe

**Comment by 14zac2** [comment]
Hi Luca - I tried running mikado with --only-reference-update and it didn't work as I'd hoped. Looking more in the command, it sounds like the flag is only looking to update loci that contain transcripts marked as "reference". I indeed was left with a very small number of genes - smaller than my initial reference set.

What I was hoping, is that marking my one gtf file as reference (yes in the 5th column of list.txt) would allow this particular set of genes and transcripts to be passed through the annotation pipeline while adding additional features and splice variants to the entire genome. I am looking to add these features because that particular gene set is about 1/3 of the entire set but of very good quality.

I am currently attempting to induce this behaviour by setting the score in list.txt to something obnoxiously high. However, I just changed the value from 5 to 50 and this didn't change anything, so I'm a bit concerned about this. Please let me know if you update anything to make it possible!

Thanks again,
Zoe

**Comment by lucventurini** [comment]
> 
> 
> Hi Luca - I tried running mikado with --only-reference-update and it didn't work as I'd hoped. Looking more in the command, it sounds like the flag is only looking to update loci that contain transcripts marked as "reference". I indeed was left with a very small number of genes - smaller than my initial reference set.
> 
> What I was hoping, is that marking my one gtf file as reference (yes in the 5th column of list.txt) would allow this particular set of genes and transcripts to be passed through the annotation pipeline while adding additional features and splice variants to the entire genome. I am looking to add these features because that particular gene set is about 1/3 of the entire set but of very good quality.
> 
> I am currently attempting to induce this behaviour by setting the score in list.txt to something obnoxiously high. However, I just changed the value from 5 to 50 and this didn't change anything, so I'm a bit concerned about this. Please let me know if you update anything to make it possible!
> 
> Thanks again,
> Zoe

Hi Zoe,

sorry to hear this. Yes, you are right in pointing out that Mikado under-performs in this kind of scenario. I am sorry I provided partial advice in my previous comment.

To be more clear, at the moment switching the "only-reference-update" flag on has only two effects:

- it infuences the padding and allows reference transcripts to be modified by enlarging their UTRs
- it removes any locus where no transcript is part of the provided reference

This is, of course, far from what you want to achieve and is a distinct feature miss by Mikado.

Improving it so that it can perform an annotation update like PASA or MAKER has been on our wishlist for a while. I will see how difficult it might be to implement, but I cannot make promises on the timeline, unfortunately, as I have other commitments on other projects.

@swarbred , would you be able to comment any futher by any chance?

Many thanks

Luca Venturini

**Comment by swarbred** [comment]
>What I was hoping, is that marking my one gtf file as reference (yes in the 5th column of list.txt) would allow this particular set of genes and transcripts to be passed through the annotation pipeline while adding additional features and splice variants to the entire genome. I am looking to add these features because that particular gene set is about 1/3 of the entire set but of very good quality.


Hi Zoe, what you want to do is one of the ways we use mikado. What you are doing seems correct but I will summarise here and you can confirm if this is the case.

In the list file:

set is_reference to "True" for the transcript set/s you want to mark as reference
set score to something like "30" will be fine with the provided scoring file

generate the configuration file using this list.txt file with mikado configure (also use the --full option to get the full parameters) you should see these these transcript sets marked as true for reference in the configuration

e.g.
`reference = [false, false, false, false, true]`

and also the scores added under the 

`prepare.files.source_score`

section

This will ensure one of the models from the "reference" set will be assigned as the primary model at each resolved loci (i.e. highest scoring primary=True in the mikado.loci.gff3).

In the configuration file i.e. configuration.toml:

change min_score_perc = 0.5 to

`min_score_perc = 0.1`

otherwise you will filter out many non reference transcripts on score 

The default in the config is only_reference_update = false

set as false if you also want to return transcripts relating to novel loci i.e. those that don't contain a reference model 
set as true aif you want loci that dont have a reference transcript to be excluded.


The above should assuming all the input models have CDS features ensure that a reference model is set as the primary for each loci (when a reference model is present), splice variants from other reference models or from the non-reference transcripts will be added based on the 

pick.alternative_splicing options in the configuration.toml

for example you may want to adjust
min_cds_overlap = 0.5
min_cdna_overlap = 0.6

and the 

as_requirements:

in the scoring file as these will filter both reference and non-reference transcripts

This should lead to the vast majority of reference models being present in the final mikado.loci.gff3 file. You may lose some models that dont follow how mikado defines separate genes i.e. if the input annotation has different genes that share splice sites but these will be edge cases.

I have used mikado to do exactly what you are attempting so this should work. If not I would suggest running mikado pick on just a small region i.e. a few genes that dont behave as you expect using the pick -r option that way you can quickly check the effect of changing the config and scoring. It's also useful to output --subloci-out and --monoloci-out as these give the scoring at intermediary steps.

Let us know how you get on and we will try to help you work out the issue.

David

https://www.earlham.ac.uk/genome-annotation-workshop-2021 for details of our virtual annotation workshop in 2021

**Comment by 14zac2** [comment]
Hi David and Luca,

Thank you so much for your patience and generosity with your time in helping me with this issue! I'm happy to say that I am now receiving my desired outcome, as my entire curated gene set is retained! I had made the major mistake of ramping up the scores in list.txt but I didn't rerun mikado configure - such a dumb mistake!! Now that I am actually using mikado properly, it's certainly working well for me.

I also investigated those parameters you mentioned, David, and I was able to figure out how to tweak all of them expect for min_score_perc. For some reason I couldn't find this for the lift of me in the mikado configure option or after copying over the mammalian.yaml scoring file. However, considering the way I have the scores is working now, perhaps I don't need to tweak it.

Thanks again,
Zoe

**Comment by swarbred** [comment]
Hi Zoe,

This is the relevant section for min_score_perc (this is the default toml format configuration, you should get all options with --full when running configure)

```

[pick.alternative_splicing]
# Parameters related to alternative splicing reporting.
# - report: whether to report at all or not the AS events.
# - min_cds_overlap: minimum overlap between the CDS of the primary transcript and any AS event. Default: 60%.
# - min_cdna_overlap: minimum overlap between the CDNA of the primary transcript and any AS event.
# Default: 0% i.e. disabled, we check for the CDS overlap.
# - keep_retained_introns: Whether to consider as valid AS events where one intron
# - max_isoforms: Maximum number of isoforms per locus. 1 implies no AS reported. Default: 5
# is retained compared to the primary or any other valid AS. Default: false.
# - valid_ccodes: Valid class codes for AS events. Valid codes are in categories
# 'Alternative splicing', 'Extension' (with junction F1 lower than 100%), and Overlap (exluding m). Default: j, J, g, G, C, h
# - max_utr_length: Maximum length of the UTR for AS events. Default: 10e6 (i.e. no limit)
# - max_fiveutr_length: Maximum length of the 5'UTR for AS events. Default: 10e6 (i.e. no limit)
# - max_threeutr_length: Maximum length of the 5'UTR for AS events. Default: 10e6 (i.e. no limit)
# - min_score_perc: Minimum score threshold for subsequent AS events. Only transcripts with a score at least (best) * value are retained.
# - only_confirmed_introns: bring back AS events only when their introns are either present in the primary transcript or in the set of confirmed introns.
# - pad: boolean switch. If true, Mikado will pad all the transcript in a gene so that their ends are the same
# - ts_distance: if padding, this is the maximum distance in base-pairs between the starts of transcripts to be considered to be padded together.
# - ts_max_splices: if padding, this is the maximum amount of splicing junctions that the transcript to pad is allowed to cross. If padding would lead to cross more than this number, the transcript will not be padded.
report = true
min_cds_overlap = 0.5
min_cdna_overlap = 0.6
keep_retained_introns = true
keep_cds_disrupted_by_ri = false
max_isoforms = 10
valid_ccodes = ["j", "J", "G", "h"]
redundant_ccodes = ["c", "m", "_", "=", "n"]
min_score_perc = 0.5
only_confirmed_introns = true
ts_distance = 2000
pad = true
ts_max_splices = 2

```

If you are running --full and dont see this option that would be strange as I don't think we have changed the option recently.

**Comment by 14zac2** [comment]
Not using the --full flag was my mistake! I see the option now, and appreciate your help, again. Looking forward to using your tool with my work!

Zoe

**Comment by lucventurini** [comment]
Dear @14zac2 

I have started working on a new branch of Mikado, `issue-340-reference-update`, to make the process easier. I hope to have some good progress on it quickly. The goal is to bring this feature fully to Mikado, rather than having to resort to the workaround tried and tested by @swarbred.

I will update when I have news on functioning code (hopefully soon).

Kind regards

Luca Venturini

**Comment by 14zac2** [comment]
Hi Luca,

That sounds fantastic!! No worries at all, now that I have figured out how to use this work-around, but I do think this feature will be very useful for future annotation assemblies!

Thanks again,
Zoe

**Comment by lucventurini** [comment]
@gemygk @swarbred @ljyanesm 

Commit 27705b0 should fix the issue, by establishing the following:

- Two flags: `reference-update` and `only-reference-update` (both in the config file and in the CLIs). The latter is a more stringent version of the former, in that any locus *without* a reference transcript will be discarded at the end.
- In a reference update run, in any locus with reference transcripts, after the sublocus stage, any non-reference will be ignored before reaching the AS stage *if there are reference transcripts around*.
  - note that this means that non-reference transcripts might still end up in their own locus!
- Reference transcripts **do not need** to have a bump in the scoring. Actually I probably would discourage that as it makes difficult to grade any other transcript in the locus (e.g. @swarbred 's suggestion to lower the "min_score_threshold" to 10%).
- At the AS stage, reference transcripts will *not* count towards the maximum number of isoforms in a locus. Relatedly, they will not have to pass the "min_score_threshold" check.
- Reference AS transcripts *will* have to pass the min_cds_overlap, min_cdna_overlap, and general class code checks - both to verify that they are valid AS forms as well as to check that they are not redundant with other transcript in the locus.

Please let me know whether any of this should be amended.

@14zac2 

Hopefully once this is finalised it will provide a more intuitive and easier way to achieve what you were after.

Many thanks,
Luca Venturini

**Comment by 14zac2** [comment]
Brilliant, thank you for the detailed thought and attention you have put into this! It is much appreciated.
