### ISSUE TITLE
Bug report on the mikado util stats comand 

### ISSUE THREAD

**Issue by RogerioRibeiro201505534** [EI-CoreBioinformatics/mikado#386]
Hi, 
Recently I found a weird results on my assembly stats file. This line here: 

`Exons per transcript (mRNAs)    3201    6.15    2.0     1       1       1       2       3       5       8       12      16      24      78`

Show that my annotation only has 3201 exons in total (unless I am misinterpreting anything). This is nonsensical since my transcriptome has around 55K coding transcripts

This is the command I used: `mikado util stats mikado.loci.gff3 mikado.loci.stats.tsv`
where mikado.loci.gff3 is the output of the mikado run 

I'm using mikado 2.1.1. 
This is not a deal-breaking bug, but thought I should report it anyway

**Comment by lucventurini** [comment]
Dear @RogerioRibeiro201505534 

Many thanks for reporting this, we will have a look forthwith.

Kind regards

**Comment by lucventurini** [comment]
Hi @RogerioRibeiro201505534 

I think that the issue might be that your file is not sorted in the expected way (gene before transcript, transcript before exon). Mikado historically has had some issues with files that are not sorted like that but rather e.g. lexicographic order.

I am updating the code of the stats utility so that it can deal with unsorted input.

Best
