### ISSUE TITLE
Merge bams or each bam separately?

### ISSUE THREAD

**Issue by xiekunwhy** [EI-CoreBioinformatics/mikado#425]
Hi,

If I have several RNA data sets (for example, different tissues or biological repeats), so I have 3 options to use these data sets to assemble transcripts,
1) Merge all raw reads and then map on to reference then assemble transcripts (or merge all bams after mapping each data set separately and then assemble transcripts using merged bam), then mikado, this is the PASA's method.
2) Map and assemble and mikado each data set separately, and then combine mikado results (how to?);
3) Map and assemble each data set separately, then mikado all the assemblies.

Which way is the best way, and why?

Best,
Kun

**Comment by lucventurini** [comment]
Hi @xiekunwhy ,

The correct way for Mikado is number 3. If you merge data from different samples, you increase the coverage of low-expression transcripts (therefore improving the possibility of detecting them) but at the much higher cost of making it more difficult to reconstruct transcript isoforms when they differ between samples.

Briefly, usually cells express one transcript isoform, so given decent levels of expression, an assembler should be able to reconstruct them. But merging data together can confuse them as suddenly many more potential isoforms are reconstructable from the data (many of them being artefacts due to the uneven coverage).

Mikado was written to be able to perform the analysis _a posteriori_, with all the data aligned separately. The `mikado prepare` step has precisely the aim of bringing together multiple assemblies into a coherent input for the rest of the pipeline.

**Comment by lucventurini** [comment]
PS: more details can be found in our original publication:

https://academic.oup.com/gigascience/article/7/8/giy093/5057872?login=true

**Comment by xiekunwhy** [comment]
Hi @lucventurini ,

Thank you for your detail reply. I have some other questions
1) In https://mikado.readthedocs.io/en/stable/Tutorial/, there are "transcript" features in trinity.gff3, but I can not find "transcript" features any more when I use latest version of gmap(Version 2021-12-12) with -f 2, will this affect the mikado results? And which features in gff/gtf file are useful for mikado?
2) Have you red this paper about transuite(https://www.biorxiv.org/content/10.1101/2020.12.15.422989v1), it is faster and more accurately than transdecoder according to this preprint paper. Do you think it is a good alternative tool for transdecoder.
3) Can I use orthodb10 as homology database instead of SwissProt, which one is better in your mind?
4) Time consuming of each step, would you please have a brief intruduction of time consuming in each mikado's step (use H. sapiens in original publication as a case), this may help me to jude status of my jobs.

Best,
Kun

**Comment by xiekunwhy** [comment]
Hi @lucventurini ,

Most of questions above have been solved after reading through the turorial and running the pipeline.

But I still don't know how to use multiple portcullis bed files because --junctions option in configure stage can only accept one file a time, would you please explain how to combine multiple portcullis bed files together?

Best,
Kun

**Comment by swarbred** [comment]
@xiekunwhy 

Delayed reply but you can use junctools (included with portcullis) to combine the pass junctions

junctools set --operator=max union
